#!/bin/bash

echo "🚀 RAG Stack Generator - Deployment Script"
echo "==========================================="

# Test local build first
echo "📦 Testing local build..."
npm run build:server
if [ $? -ne 0 ]; then
    echo "❌ Local build failed. Please fix errors before deploying."
    exit 1
fi

echo "✅ Local build successful!"

echo ""
echo "🎯 Ready for deployment! Here are your options:"
echo ""
echo "1️⃣  DIGITALOCEAN APP PLATFORM (RECOMMENDED):"
echo "   - Go to: https://cloud.digitalocean.com/apps"
echo "   - Create new App"
echo "   - Connect repository: Amarnathss/RAGStackGen"
echo "   - Build command: npm run build && cd dist && npm install --production"
echo "   - Run command: npm start (serves full-stack app)"
echo "   - Port: 5000"
echo "   - Use .do/app.yaml for automatic configuration"
echo "   - Result: Single URL serves both frontend and API"
echo ""
echo "2️⃣  RENDER BACKEND DEPLOYMENT:"
echo "   - Go to: https://render.com"
echo "   - Create new Web Service"
echo "   - Connect repository: Amarnathss/RAGStackGen"
echo "   - Build command: npm run build:server"
echo "   - Start command: npm start"
echo ""
echo "3️⃣  MANUAL FRONTEND DEPLOYMENT (Only if needed separately):"
echo "   - Run: npm run build:frontend"
echo "   - Run: cd client && vercel --prod"
echo "   - Set VITE_API_URL to your backend URL"
echo ""
echo "🔑 Environment Variables for DigitalOcean App Platform:"
echo "   NODE_ENV=production"
echo "   DATABASE_URL=your_neon_database_url"
echo "   GROQ_API_KEY=your_groq_api_key"
echo "   GITHUB_TOKEN=your_github_token"
echo "   JWT_SECRET=your_jwt_secret"
echo "   PORT=5000"
echo ""
echo "🔑 Environment Variables for Render:"
echo "   NODE_ENV=production"
echo "   DATABASE_URL=your_neon_database_url"
echo "   GROQ_API_KEY=your_groq_api_key"
echo "   GITHUB_TOKEN=your_github_token"
echo "   JWT_SECRET=your_jwt_secret"
echo "   FRONTEND_URL=https://your-vercel-app.vercel.app"
echo ""
echo "🔑 Environment Variables for Vercel (if deploying frontend separately):"
echo "   VITE_API_URL=https://your-digitalocean-app.ondigitalocean.app"
echo ""
echo "📱 Quick Start for DigitalOcean App Platform (Full-Stack):"
echo "   1. Fork/push this repository to GitHub"
echo "   2. Visit https://cloud.digitalocean.com/apps"
echo "   3. Click 'Create App' and connect your repository"
echo "   4. DigitalOcean will auto-detect the .do/app.yaml configuration"
echo "   5. Add the environment variables listed above"
echo "   6. Deploy!"
echo "   7. Your app will be available at: https://your-app.ondigitalocean.app"
echo "      - Frontend: https://your-app.ondigitalocean.app"
echo "      - API: https://your-app.ondigitalocean.app/api/*"
echo ""
echo "✅ Single deployment - frontend and backend served together!"
